"""Add File and FileProcess tables and update User relationships

Revision ID: ca2f89d387b4
Revises: 1a31ce608336
Create Date: 2025-05-23 20:11:29.600443

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ca2f89d387b4'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('minio_object_name', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('upload_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('upload_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_id'), 'file', ['id'], unique=False)
    op.create_index(op.f('ix_file_minio_object_name'), 'file', ['minio_object_name'], unique=True)
    op.create_index(op.f('ix_file_original_filename'), 'file', ['original_filename'], unique=False)
    op.create_index(op.f('ix_file_user_id'), 'file', ['user_id'], unique=False)
    op.create_table('fileprocess',
    sa.Column('process_type', sa.Enum('TRANSCRIPTION', 'ANALYSIS', 'UNKNOWN', name='processtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='processstatus'), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fileprocess_file_id'), 'fileprocess', ['file_id'], unique=False)
    op.create_index(op.f('ix_fileprocess_id'), 'fileprocess', ['id'], unique=False)
    op.create_index(op.f('ix_fileprocess_process_type'), 'fileprocess', ['process_type'], unique=False)
    op.create_index(op.f('ix_fileprocess_status'), 'fileprocess', ['status'], unique=False)
    op.create_index(op.f('ix_fileprocess_user_id'), 'fileprocess', ['user_id'], unique=False)
    op.drop_constraint('item_owner_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_owner_id_fkey', 'item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_fileprocess_user_id'), table_name='fileprocess')
    op.drop_index(op.f('ix_fileprocess_status'), table_name='fileprocess')
    op.drop_index(op.f('ix_fileprocess_process_type'), table_name='fileprocess')
    op.drop_index(op.f('ix_fileprocess_id'), table_name='fileprocess')
    op.drop_index(op.f('ix_fileprocess_file_id'), table_name='fileprocess')
    op.drop_table('fileprocess')
    op.drop_index(op.f('ix_file_user_id'), table_name='file')
    op.drop_index(op.f('ix_file_original_filename'), table_name='file')
    op.drop_index(op.f('ix_file_minio_object_name'), table_name='file')
    op.drop_index(op.f('ix_file_id'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
